# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-10-24 23:13
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app03plus', '0002_auto_20181024_2255'),
    ]

    operations = [
        migrations.AddField(
            model_name='stu',
            name='name',
            field=models.CharField(default=0, max_length=30),
        ),
        migrations.AlterField(
            model_name='grade',
            name='name',
            field=models.CharField(default=0, max_length=20),
        ),
        migrations.AlterField(
            model_name='stu',
            name='grade',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='app03plus.Grade'),
        ),
    ]
