# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-10-24 23:14
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app03plus', '0003_auto_20181024_2313'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stu',
            name='grade',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app03plus.Grade'),
        ),
    ]
