# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-10-25 01:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app03plus', '0005_author_book'),
    ]

    operations = [
        migrations.AlterField(
            model_name='grade',
            name='name',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='stu',
            name='name',
            field=models.CharField(max_length=30),
        ),
    ]
