# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-10-25 01:38
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app03plus', '0006_auto_20181025_0125'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stu',
            name='grade',
        ),
        migrations.DeleteModel(
            name='Grade',
        ),
        migrations.DeleteModel(
            name='Stu',
        ),
    ]
