# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-11-06 10:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app10', '0003_auto_20181105_2150'),
    ]

    operations = [
        migrations.CreateModel(
            name='MineBtns',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('btn', models.CharField(max_length=30)),
                ('class_name', models.CharField(max_length=100)),
                ('bref_url', models.CharField(max_length=255, null=True)),
                ('is_used', models.BooleanField(default=True, verbose_name='是否正在使用')),
            ],
            options={
                'verbose_name': '我的页面的下一排按钮',
            },
        ),
    ]
