# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-11-06 10:19
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app10', '0004_minebtns'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='minebtns',
            name='is_used',
        ),
    ]
