# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-10-23 15:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app02', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(db_column='cate_name', max_length=30, verbose_name='分类名'),
        ),
        migrations.AlterModelTable(
            name='category',
            table='category',
        ),
    ]
